version: '3'
volumes:
  postgis-data:

services:

  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./sql/00_drop.sql:/docker-entrypoint-initdb.d/00_drop.sql
      - ./sql/10_tonttijakosuunnitelma.sql:/docker-entrypoint-initdb.d/10_tonttijakosuunnitelma.sql
#      - ./sql/12_kiinteisto.sql:/docker-entrypoint-initdb.d/12_kiinteisto.sql
      - ./sql/20_data_tonttijakosuunnitelma.sql:/docker-entrypoint-initdb.d/20_data_tonttijakosuunnitelma.sql
#      - ./sql/22_data_kiinteisto.sql:/docker-entrypoint-initdb.d/22_data_kiinteisto.sql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=tre_kiintmuod
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # if true, table initializations are run each time from /docker-entrypoint-initdb.d
      # Warning: does not seem to work consistently. See README for updated instructions
      - IGNORE_INIT_HOOK_LOCKFILE=true
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis, "uuid-ossp"
    ports:
      - 5432:5432
    restart: on-failure

  schema_image:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
      - ./schemaspy.properties:/schemaspy.properties
    environment:
      WAIT_HOSTS: db:5432

  flyway:
    image: flyway/flyway
    command: -baselineOnMigrate="true" migrate -X -outputType=json
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/flyway.conf:/flyway/flyway.conf
    depends_on:
      - db

  flyway_info:
    image: flyway/flyway
    command: info
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/flyway.conf:/flyway/flyway.conf
    depends_on:
      - db