version: '3'
volumes:
  postgis-data:

services:
  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=dev_alueraja_db
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis, "uuid-ossp"
    ports:
      - 5432:5432
    restart: on-failure
