INSERT INTO tonttijakosuunnitelman_laji (koodi, arvo) VALUES 
    (3002, 'Asemakaavaan sisältyvä sitova tonttijako'),
    (3003, 'Erillinen sitova tonttijako'),
    (3004, 'Sitova kolmiulotteinen tonttijako');

INSERT INTO tonttijakosuunnitelman_elinkaaren_tila (koodi, arvo) VALUES
    (4, 'Vireillä oleva tonttijakosuunnitelma'),
    (6, 'Hyväksytty tonttijakosuunnitelma'),
    (100, 'Kumottu'),
    (101, 'Rauennut'),
    (102, 'Kumottu osittain');

INSERT INTO olotila (koodi, arvo) VALUES
    (1, 'Voimassaoleva'),
    (2, 'Lakannut');

INSERT INTO suhde_peruskiinteistoon (koodi, arvo) VALUES
    (101, 'Alapuolinen'),
    (102, 'Yläpuolinen');

INSERT INTO rajamerkkityyppi (koodi, arvo) VALUES
    (1, 'Tonttipyykki'),
    (2, 'Yleisen alueen pyykki'),
    (3, 'Maarekisteripyykki'),
    (4, 'Rajapiste'),
    (5, 'Tuntematon'),
    (6, 'Rajaviitta'),
    (7, 'Suuntapyykki'),
    (8, 'Tiealueen paalu'),
    (9, 'Esitonttirajamerkki');

INSERT INTO asiakirjalaji (koodi, arvo) VALUES
    (1, 'Rajamerkkiluettelo'),
    (2, 'Laskupaperi'),
    (3, 'Muodostusluettelo'),
    (4, 'Tonttijakosuunnitelmakartta');

INSERT INTO rekisteriyksikkolaji (koodi, arvo) VALUES
    (1, 'Tila'),
    (3, 'Valtion metsämaa'),
    (4, 'Lunastusyksikkö'),
    (7, 'Erillinen vesijättö'),
    (8, 'Yleinen vesialue'),
    (10, 'Yhteismetsä'),
    (12, 'Lakkautettu tie- tai liitännäisalue'),
    (13, 'Tontti'),
    (14, 'Yleinen alue'),
    (17, 'Yhteinen vesialue'),
    (18, 'Yhteinen maa-alue'),
    (19, 'Suojelualuekiinteistö'),
    (21, 'Tie- tai liitännäisalue tieoikeudella'),
    (22, 'Tie- tai liitännäisalue omistusoikeudella');

INSERT INTO rekisteriyksikon_elinkaaren_tila (koodi, arvo) VALUES
    (1, 'Luonnos'),
    (2, 'Esirekisteritila'),
    (3, 'Rekisteröity'),
    (4, 'Lakannut');

INSERT INTO yleisen_alueen_tyyppi (koodi, arvo) VALUES
    (9901, 'K katu'),
    (9902, 'G tori'),
    (9903, 'P puisto'),
    (9904, 'U urheilualue'),
    (9905, 'R retkeilyalue'),
    (9906, 'L loma-alue'),
    (9907, 'V vaara-alue'),
    (9908, 'E erityisalue'),
    (9909, 'W vesialue');

INSERT INTO kayttooikeusyksikkolaji (koodi, arvo) VALUES
    (101, 'Talousveden ottaminen'),
    (102, 'Talousveden johtaminen'),
    (103, 'Vesijohto'),
    (104, 'Veden johtaminen maan kuivattamista varten'),
    (105, 'Viemärijohto'),
    (106, 'Puhelinjohto'),
    (107, 'Sähköjohto'),
    (108, 'Kaasujohto'),
    (109, 'Lämpöjohto'),
    (110, 'Johto'),
    (112, 'Venevalkama'),
    (114, 'Laituri'),
    (115, 'Uimapaikka'),
    (116, 'Puutavaran varastointi'),
    (117, 'Lastauspaikka'),
    (118, 'Kalastusta varten tarvittava alue'),
    (119, 'Kiven ottaminen'),
    (120, 'Soran ottaminen'),
    (121, 'Hiekan ottaminen'),
    (122, 'Saven ottaminen'),
    (123, 'Turpeen ottaminen'),
    (124, 'Maa-aineksen ottaminen'),
    (125, 'Väestösuojelua varten tarvittava rakennelma'),
    (126, 'Kiinteistöjen yhteinen lämpökeskus'),
    (127, 'Jätteiden kokoamispaikka'),
    (128, 'Kulkuyhteys asemakaava-alueella'),
    (130, 'Sadevesiviemäri'),
    (131, 'Jäteveden johtaminen ja käsittely'),
    (132, 'Ajoneuvojen pitäminen'),
    (133, 'Venevalkama ja ajoneuvojen pitäminen'),
    (134, 'Ajoneuvojen pitäminen, venevalkama ja laituri'),
    (135, 'Yhteispiha'),
    (9101, 'Talousveden ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9102, 'Talousveden johtaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9103, 'Vesijohto, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9104, 'Veden johtaminen maan kuivattamista varten, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9105, 'Viemärijohto, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9106, 'Puhelinjohto, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9107, 'Sähköjohto, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9108, 'Kaasujohto, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9109, 'Lämpöjohto, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9110, 'Johto, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9111, 'Autojen pitäminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9112, 'Venevalkama, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9113, 'Venevalkama ja autojen pitäminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9114, 'Laituri, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9115, 'Uimapaikka, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9116, 'Puutavaran varastointi, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9117, 'Lastauspaikka, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9118, 'Kalastusta varten tarvittava alue, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9119, 'Kiven ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9120, 'Soran ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9121, 'Hiekan ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9122, 'Saven ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9123, 'Turpeen ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9124, 'Maa-aineksen ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9125, 'Väestösuojelua varten tarvittava rakennelma, kaikkia oikeutettuja, Lakannut'),
    (9126, 'Kiinteistöjen yhteinen lämpökeskus, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9127, 'Jätteiden kokoamispaikka, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9128, 'Kulkuyhteys asemakaava-alueella, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9129, 'Autojen pitäminen, venevalkama ja laituri, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9130, 'Sadevesiviemäri, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9190, 'Veden ottaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9191, 'Veden johtaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9192, 'Veden patoaminen, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9193, 'Kalastus, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9194, 'Muuntaja, kaikkia oikeutettuja ei ole selvitetty, Lakannut'),
    (9301, 'Tieoikeus, kaikkia oikeutettuja ei ole selvitetty, Lakannut');

INSERT INTO rakenne (koodi, arvo) VALUES
    (1, 'Putki'),
    (2, 'Pultti'),
    (3, 'Yksikivinen'),
    (4, 'Nelikulmainen'),
    (5, 'Viisikivinen'),
    (6, 'Yksipaaluinen'),
    (7, 'Viisipaaluinen'),
    (8, 'Reikä, ura, putki, pultti'),
    (9, 'Peräkkäiset kivet'),
    (10, 'Peräkkäiset puupaalut'),
    (11, 'Oja');

INSERT INTO maaraalan_olotila (koodi, arvo) VALUES
    (1, 'Erottamaton'),
    (2, 'Muodostettu osittain rekisteriyksiköksi'),
    (3, 'Lakannut'),
    (4, 'Virheellisesti rekisteröity');

INSERT INTO olemassaolo (koodi, arvo) VALUES
    (1, 'Tuntematon'),
    (2, 'Olemassa'),
    (3, 'Kadonnut'),
    (4, 'Ei rakennettu');

INSERT INTO nakyvyys (koodi, arvo) VALUES
    (1, 'Tuntematon'),
    (2, 'Näkyvissä'),
    (3, 'Upotettu');

INSERT INTO alusta (koodi, arvo) VALUES
    (1, 'Ei tietoa'),
    (2, 'Kallio'),
    (3, 'Maaperäkivi'),
    (4, 'Sokkeli'),
    (5, 'Seinä'),
    (6, 'Katto'),
    (7, 'Asfaltti'),
    (8, 'Puu'),
    (9, 'Maaperä');

INSERT INTO toimenpidelaji (koodi, arvo) VALUES
    (301, 'Luovutetun määräalan rekisteröinti'),
    (302, 'Määräalan tietojen korjaus'),
    (303, 'Virheen korjaus, määräala siirretty toiseen yksikköön'),
    (304, 'Määräalan rekisteröinti uudella tunnuksella'),
    (305, 'Määräalan sijainnin korjaus yksikön alueella'),
    (306, 'Määräalan poisto (luovutus purettu)'),
    (307, 'Virheellisesti rekisteröidyn määräalan poisto'),
    (308, 'Määräalan lakkauttamisen peruminen'),
    (309, 'Määräalan sijainnin lisäys'),
    (310, 'Määräalan sijainnin poisto'),
    (311, 'Määräalan kohdistaminen uudelle yksikölle'),
    (312, 'Määräalan kohdistamisen peruminen'),
    (313, 'Rekisteriyksikön omistajalle siirtyneen määräalan poisto'),
    (314, 'Määräala luovutettu kokonaan osamääräaloiksi'),
    (315, 'Määräalan poisto rekisterinpitäjän päätöksellä'),
    (320, 'Määräalan sijainnin siirto muuttuneen kiinteistojaon vuoksi'),
    (325, 'Määräalan alkuperäisen luovuttajan korjaus'),
    (326, 'Määräalan alkuperäisen saajan korjaus'),
    (1001, 'Oikeuden perustaminen'),
    (1002, 'Oikeuden säilyttäminen'),
    (1003, 'Käyttöoikeuden perustaminen'),
    (1005, 'Merkinnän perustaminen'),
    (1006, 'Merkinnän säilyttäminen'),
    (1007, 'Kaavamerkinnän lisääminen'),
    (1008, 'Kaavamerkinnän kohdistaminen'),
    (1011, 'Oikeuden poisto päätöksellä'),
    (1013, 'Merkinnän poisto päätöksellä'),
    (1016, 'Ylimääräisen oikeuden poisto'),
    (1017, 'Ylimääräisen merkinnän poisto'),
    (1018, 'Virheellisen oikeuden poisto'),
    (1019, 'Virheellisen merkinnän poisto'),
    (1020, 'Rauenneen oikeuden poisto'),
    (1025, 'Käyttöoikeuden kohdistaminen'),
    (1031, 'Sijainnin muuttaminen'),
    (1032, 'Sijainnin lisääminen'),
    (1033, 'Sijainnin poistaminen'),
    (1041, 'Määräaikaistaminen'),
    (1042, 'Määräajan muuttaminen'),
    (1043, 'Määräajan poisto'),
    (1044, 'Oikeuden ulottuvuuden muuttaminen'),
    (1045, 'Rasitemerkinnän täydentäminen'),
    (1049, 'Osuusmerkinnän jakautumisperusteen poisto'),
    (1051, 'Koko merkinnän muutos käyttöoikeusyksiköksi'),
    (1053, 'Koko merkinnän muutos yhteisalueosuudeksi'),
    (1054, 'Merkinnän osan muutos yhteisalueosuudeksi'),
    (1061, 'Hallintokunnan lisääminen käyttöoikeusyksikölle'),
    (1062, 'Hallintokunnan poisto käyttöoikeusyksiköltä'),
    (1071, 'Hallintokunnan perustaminen'),
    (1072, 'Hallintokunnan tietojen täydennys'),
    (1073, 'Yhteyshenkilön poisto hallintokunnalta'),
    (1074, 'Tiekunnan säännöt'),
    (1075, 'Tiekunnan sääntöjen poistaminen'),
    (1076, 'Tiekunnan päätös'),
    (1080, 'Viranomaispäätöksen lisääminen'),
    (1081, 'Rakennuskiellon lisääminen'),
    (1082, 'Rakennuskiellon poisto'),
    (1083, 'Rakennuskiellon kohdistaminen'),
    (1084, 'Tonttijaon lisääminen'),
    (1086, 'Tonttijaon kohdistaminen'),
    (1087, 'Kumotun kaavan poisto'),
    (1088, 'Kumotun tonttijaon poisto'),
    (1091, 'Rajausselityksen lisääminen'),
    (1092, 'Rajausselityksen poisto'),
    (1093, 'Rajausselityksen muuttaminen'),
    (1101, 'Lohkominen'),
    (1191, 'Tontin lohkominen'),
    (1192, 'Yleisen alueen lohkominen'),
    (1193, 'Tontin lohkominen ja tontinosan lunastaminen'),
    (1210, 'Halkominen'),
    (1220, 'Yhteishalkominen'),
    (1251, 'Jakosuunnitelma koko rekisteriyksiköllä'),
    (1252, 'Jakosuunnitelma osalla rekisteriyksikköä'),
    (1310, 'Tilusvaihto'),
    (1411, 'Erillisen vesijätön kiinteistöön liittäminen'),
    (1412, 'Erillisen vesijätön tilaksi muodostaminen'),
    (1430, 'Muun erillisen alueen tilaksi muodostaminen'),
    (1440, 'Muun erillisen alueen kiinteistöön liittäminen'),
    (1450, 'Yleiseen tarpeeseen erotetun alueen muodostaminen rekisteriyksiköksi'),
    (1451, 'Yleiseen tarpeeseen erotetun alueen liittäminen tilaan'),
    (1605, 'Yhteisen alueen muodostaminen'),
    (1607, 'Yhteisen alueen jako'),
    (1608, 'Yhteisen alueen jako ja kiinteistöön liittäminen'),
    (1610, 'Yhteisalueosuuden siirto'),
    (1615, 'Yhteismetsäosuuden siirto'),
    (1616, 'Yhteistä erityistä etuutta koskevan osuuden siirto'),
    (1620, 'Yhteisalueosuuden tilaksi muodostaminen'),
    (1621, 'Yhteismetsäosuuden tilaksi muodostaminen'),
    (1622, 'Yhteistä erityistä etuutta koskevan osuuden tilaksi muodostaminen'),
    (1630, 'Ylimääräisen osuusmuutoksen poisto'),
    (1631, 'Virheellisen osuusmuutoksen poisto'),
    (1632, 'Ylimääräisen osakkuuden poisto'),
    (1633, 'Virheellisen osakkuuden poisto'),
    (1634, 'Osakasluettelon perustaminen'),
    (1635, 'Tarpeettoman osakasluettelon poisto'),
    (1636, 'Virheellisen osakasluettelon poisto'),
    (1637, 'Osakasluettelon vahvistaminen'),
    (1639, 'Osakasluettelon täydentäminen'),
    (1640, 'Osakaskunnan poisto osakasluettelolta'),
    (1641, 'Osakaskunnan perustaminen'),
    (1642, 'Osakaskunnan tietojen täydennys'),
    (1643, 'Yhteyshenkilön poisto osakaskunnalta'),
    (1644, 'Puuttuvan osakkaan lisääminen'),
    (1645, 'Osakaskunnan lisääminen osakasluettelolle'),
    (1650, 'Yhteisen erityisen etuuden muodostaminen'),
    (1710, 'Vesijätön lunastus'),
    (1720, 'Yhteisen alueen lunastus'),
    (1730, 'Rakennuspaikan osan lunastus'),
    (1740, 'Alueen lunastus'),
    (1741, 'Alueen lunastus ja liittäminen'),
    (1744, 'Yleisen tien lunastus ja liittäminen'),
    (1745, 'Yleisen tien lunastus'),
    (1748, 'Yleisen tien rajaaminen'),
    (1749, 'Yleisen tien rajaaminen ja liittäminen'),
    (1750, 'Alueen liittäminen yhteiseen alueeseen'),
    (1754, 'Entisen tiealueen liittäminen rekisteriyksikköön'),
    (1755, 'Lakanneen yhteisen tien tai valtaojan liittäminen'),
    (1757, 'Entisen tiealueen muodostaminen rekisteriyksiköksi'),
    (1760, 'Ulkopalstan lunastaminen'),
    (1764, 'Vähäisen alueen lunastaminen (Kiinteistönmuodostamislaki 79 §)'),
    (1770, 'Yhteisalueosuuden lunastaminen'),
    (1771, 'Yhteistä erityistä etuutta koskevan osuuden hankkiminen'),
    (1780, 'Yhteismetsän muodostaminen'),
    (1782, 'Yhteismetsään liittäminen osuutta vastaan'),
    (1784, 'Yhteismetsäosuuden siirto osakaskunnalle'),
    (1790, 'Maantien rajaaminen'),
    (1791, 'Maantien rajaaminen ja liittäminen'),
    (1792, 'Tieoikeusalueen liittäminen rekisteriyksikköön'),
    (1793, 'Tieoikeusalueen muodostaminen rekisteriyksiköksi'),
    (1796, 'Entisen rautatiealueen liittäminen rekisteriyksikköön'),
    (1797, 'Entisen rautatiealueen muodostaminen rekisteriyksiköksi'),
    (1798, 'Rautatiealueen rajaaminen'),
    (1799, 'Rautatiealueen rajaaminen ja liittäminen'),
    (1810, 'Tontin muodostaminen tunnusmuutoksella'),
    (1900, 'Tilusjärjestely'),
    (1915, 'Rakennusmaan järjestely'),
    (1918, 'Rakennusmaan järjestely muodostaen uusi rekisteriyksikkö'),
    (2110, 'Rajankäynti'),
    (2210, 'Kartoitus kokonaan'),
    (2220, 'Kartoitus osittain'),
    (2230, 'Pinta-alan korjaus'),
    (2310, 'Rekisteriyksikön alueen selvittäminen'),
    (2520, 'Kiinteistöjaotukseen liittyvän epäselvyyden selvittäminen'),
    (2801, 'Rasitetoimitus'),
    (2802, 'Rakennusrasitepäätös'),
    (2803, 'Muu päätös'),
    (2804, 'Kiinteistörekisterinpitäjän päätös'),
    (2805, 'Rakennusvalvontaviranomaisen päätös'),
    (2806, 'Yksityistietoimitus'),
    (2807, 'Kiinteistönmääritys'),
    (2808, 'Sikseen jätetty toimitus'),
    (2809, 'Hallinnollisen kuntarajan muuttaminen'),
    (2810, 'Rasitteen käyttämistä koskevien määräysten muuttaminen'),
    (2811, 'Rasitteen poistaminen'),
    (2812, 'Tieoikeuden käyttämistä koskevien määräysten muuttaminen'),
    (2813, 'Tieoikeuden poistaminen'),
    (2814, 'Lunastustoimitus'),
    (2815, 'Lunastamalla hankitun erityisen oikeuden tai rajoituksen muuttaminen'),
    (2816, 'Lunastamalla hankitun erityisen oikeuden tai rajoituksen lakkauttaminen'),
    (3010, 'Virheen oikaisu (Kiinteistönmuodostamislaki 277.2 §)'),
    (3012, 'Aiheeton virheen oikaisumerkintä peruttu'),
    (3022, 'Aiheeton päätöksen muuttaminen peruttu'),
    (3032, 'Toimituksen purkaminen peruttu'),
    (3042, 'Päätöksen purkaminen peruttu'),
    (3100, 'Rekisterivirheen korjaaminen'),
    (3102, 'Aiheeton virheen korjaamismerkintä peruttu'),
    (3202, 'Aiheeton kiinteistörekisteristä poistaminen peruttu'),
    (3300, 'Uudelleen rekisteröinti'),
    (3302, 'Aiheeton uudelleen rekisteröinti peruttu'),
    (3500, 'Rekisterimerkintä poistettu'),
    (3502, 'Aiheeton poistaminen peruttu'),
    (3702, 'Rekisterimerkinnän aiheeton peruminen peruttu'),
    (3801, 'Virheen oikaisu (Kiinteistönmuodostamislaki 277.1 §)'),
    (3802, 'Lakkautus peruttu virheen oikaisussa (Kiinteistönmuodostamislaki 277.1 §'),
    (3803, 'Asiakirjavirheen korjaaminen (Kiinteistönmuodostamislaki 277.2'),
    (3804, 'Lakkautus peruttu asiakirjavirheen korjaamisessa (Kiinteistönmuodostamislaki 277.2 §)'),
    (3805, 'Päätöksen purkaminen (Kiinteistönmuodostamislaki 278.1 §)'),
    (3806, 'Lakkautus peruttu päätöksen purkamisessa (Kiinteistönmuodostamislaki 278.1 §)'),
    (3807, 'Toimituksen purkaminen (Kiinteistönmuodostamislaki 278.1 §)'),
    (3809, 'Rekisterivirheen korjaaminen'),
    (3810, 'Lakkautus peruttu rekisterivirheen korjauksessa'),
    (3901, 'Isojaossa syntyneen yksikön rekisteröinti'),
    (3902, 'Aikaisemmin syntyneen yksikön rekisteröinti'),
    (3920, 'Rekisteritiedon täydentäminen'),
    (3961, 'Tarpeettoman rekisteriyksikön poisto'),
    (3980, 'Lakanneen yksikön poistaminen kiinteistörekisteristä'),
    (4101, 'Rekisteriyksikköön liittäminen'),
    (4102, 'Kiinteistöjen yhdistäminen'),
    (4103, 'Yhteisten alueiden yhdistäminen'),
    (4201, 'Kuntajaon muutos'),
    (4211, 'Kameraalisen jaotuksen muutos'),
    (4221, 'Kameraalinen lohkominen'),
    (4230, 'Kameraalinen osittaminen'),
    (4232, 'Kameraalinen osittaminen ja liittäminen'),
    (4300, 'Nimen muutos'),
    (4350, 'Kiinteistön laadun muuttaminen'),
    (4400, 'Kiinteistötunnuksen muuttaminen'),
    (4650, 'Alueellinen yksityistietoimitus koko rekisteriyksiköllä'),
    (4651, 'Alueellinen yksityistietoimitus rekisteriyksikön osalla'),
    (4660, 'Erityisen oikeuden käyttötarkoituksen muuttaminen'),
    (4720, 'Muodostusluettelosta rekisteröinti'),
    (4816, 'Määräalan lunastaminen'),
    (4818, 'Korvauksen määrääminen'),
    (6051, 'Kaavan mukaisen käyttötarkoituksen lisääminen'),
    (6052, 'Kaavan mukaisen käyttötarkoituksen muuttaminen'),
    (6053, 'Kaavan mukaisen käyttötarkoituksen poistaminen'),
    (6054, 'Kaavan mukaisen käyttötarkoitusmerkinnän täydentäminen'),
    (6061, 'Henkilötietojen muuttaminen'),
    (6080, 'Ulottuvuuden muuttaminen'),
    (6081, 'Rekisteriyksiköiden päällekkäisyyden lisääminen'),
    (6082, 'Rekisteriyksiköiden päällekkäisyyden lakkauttaminen'),
    (6083, 'Rekisteriyksiköiden päällekkäisyyden muuttaminen'),
    (0, '(Tuntematon), Lakannut'),
    (1, 'Erillisen alueen kiinteistöön liittäminen, Lakannut'),
    (2, 'Erillisen vesijätön järjestely, Lakannut'),
    (3, 'Halkominen, Lakannut'),
    (4, 'Yhteishalkominen, Lakannut'),
    (5, 'Halkomisuusjako, Lakannut'),
    (6, 'Isojaon järjestely, Lakannut'),
    (7, 'Jaon täydentäminen, Lakannut'),
    (8, 'Kaivospiiritoimitus, Lakannut'),
    (9, 'Kartoitus ja alanlasku, Lakannut'),
    (10, 'Katualueen erottaminen, Lakannut'),
    (11, 'Alueen liittäminen rekisteriyksikköön, Lakannut'),
    (12, 'Lohkominen, Lakannut'),
    (13, 'Lohkominen usealla rekisteriyksiköllä, Lakannut'),
    (14, 'Luonnon muuttaminen perintöluonnoksi, Lakannut'),
    (15, 'Alueen siirtäminen lunastuksessa rekisteriyksikköön, Lakannut'),
    (16, 'Rekisterivirheen korjaaminen, Lakannut'),
    (17, 'Määräalan siirtäminen lohkomalla, Lakannut'),
    (18, 'Pinta-alojen muutos, Lakannut'),
    (19, 'Nimen muutos, Lakannut'),
    (20, 'Osuuden siirto kiinteistöön, Lakannut'),
    (21, 'Entisen tiealueen liittäminen rekisteriyksikköön, Lakannut'),
    (22, 'Oikaisutoimitus, Lakannut'),
    (23, 'Pakkolunastus, Lakannut'),
    (24, 'Pakkolunastus käyttöoikeutta supistamalla, Lakannut'),
    (25, 'Palstatilan erottaminen, Lakannut'),
    (26, 'Palstatilan itsenäistäminen, Lakannut'),
    (27, 'Palstatilan murtaminen, Lakannut'),
    (28, 'Palstatilan osittaminen, Lakannut'),
    (29, 'Piirirajankäynti, Lakannut'),
    (30, 'Rajamerkkien siirto, Lakannut'),
    (31, 'Rajankäynti, Lakannut'),
    (32, 'Rantakaavatoimitus, Lakannut'),
    (33, 'Rakennusmaan järjestely, Lakannut'),
    (34, 'Rasitteen poisto, Lakannut'),
    (35, 'Rasitetoimitus, Lakannut'),
    (36, 'Siirretty kuntaan, Lakannut'),
    (37, 'Siirretty kunnasta, Lakannut'),
    (38, 'Yksityistietoimitus, Lakannut'),
    (39, 'Yleistietoimitus, Lakannut'),
    (40, 'Tilaksi muodostaminen, Lakannut'),
    (41, 'Tilusjärjestely, Lakannut'),
    (42, 'Tilusvaihto, Lakannut'),
    (43, 'Tontinmittaus, Lakannut'),
    (44, 'Ulkoilureittitoimitus, Lakannut'),
    (45, 'Uudelleen rekisteröinti, Lakannut'),
    (46, 'Uusjako, Lakannut'),
    (47, 'Vesijätön jako, Lakannut'),
    (48, 'Vesijätön lunastaminen, Lakannut'),
    (49, 'Vuokra-alueiden järjestely, Lakannut'),
    (50, 'Kiinteistöjen yhdistäminen, Lakannut'),
    (51, 'Yhteismetsään liittäminen, Lakannut'),
    (52, 'Rekisteriyksikköön yhdistäminen, Lakannut'),
    (53, 'Yhteisen alueen jako, Lakannut'),
    (54, 'Yleisen alueen mittaus, Lakannut'),
    (55, 'Yhteisestä alueesta erottaminen, Lakannut'),
    (56, 'Kiinteistörekisteristä poistaminen, Lakannut'),
    (57, 'Vesialueen jako, Lakannut'),
    (58, 'Koko rekisteriyksikön lunastaminen, Lakannut'),
    (59, 'Osuuden siirto kiinteistöstä, Lakannut'),
    (60, 'Alueen siirtäminen rekisteriyksiköstä, Lakannut'),
    (61, 'Alueen lunastaminen rekisteriyksiköstä, Lakannut'),
    (62, 'Yhteislohkominen, Lakannut'),
    (63, 'Tontinmittaus, rekisteriyksikkö lakkautettu, Lakannut'),
    (64, 'Yleisen alueen mittaus, rekisteriyksikkö lakkautettu, Lakannut'),
    (65, 'Lakanneen yhteisen alueen siirtyminen, Lakannut'),
    (66, 'Omistusoikeuden lunastaminen lunastustoimituksessa, Lakannut'),
    (67, 'Käyttöoikeuden lunastaminen lunastustoimituksessa, Lakannut'),
    (68, 'Yhteisen alueen erottaminen kiinteistöstä, Lakannut'),
    (69, 'Rekisteriyksikön yhdistäminen tähän yksikköön, Lakannut'),
    (70, 'Uusi tontinmittaus ja pinta-alan muutos, Lakannut'),
    (71, 'Tarkistava tontinmittaus, Lakannut'),
    (72, 'KaavJL 8a luvun mukainen esitys, Lakannut'),
    (73, 'Uusi yleisen alueen mittaus ja pinta-alan muutos, Lakannut'),
    (74, 'Tarkistava yleisen alueen mittaus, Lakannut'),
    (75, 'Kiinteistötunnuksen muutos, Lakannut'),
    (76, 'Rasitetoimitus, Lakannut'),
    (77, 'Rasitteen muutos tai siirto, Lakannut'),
    (78, 'Kiinteistötuomarin suostumus, Lakannut'),
    (79, 'Rakennusrasitepäätös, Lakannut'),
    (80, 'Rak.lautakunnan tai maistraatin päätös (RakL 133 §), Lakannut'),
    (81, 'Määräys rekisteriin merkitsemisestä, Lakannut'),
    (82, 'Posti- ja lennätinlaitoksen päätös, Lakannut'),
    (83, 'Kunnanvaltuuston päätös, Lakannut'),
    (84, 'Kunnanhallituksen päätös, Lakannut'),
    (85, 'Siirtolohkominen tähän kiinteistöön, Lakannut'),
    (86, 'Siirtolohkominen tästä rekisteriyksiköstä, Lakannut'),
    (87, 'Osan muodostaminen uudeksi rekisteriyksiköksi, Lakannut'),
    (88, 'Muodostaminen uudeksi rekisteriyksiköksi, Lakannut'),
    (89, 'Tontinmittaus, muodostajakiinteistö jäi kantakiinteistöksi, Lakannut'),
    (90, 'Muu päätös, Lakannut'),
    (91, 'Kiinteistörekisterinpitäjän päätös, Lakannut'),
    (92, 'Rekisteröinti ilman mittausta kunnan kiinteistörekisteriin, Lakannut'),
    (93, 'Erillisen alueen kiinteistöön liittäminen, Lakannut'),
    (94, 'Yhteisalueosuuden siirtäminen osakaskiinteistöille, Lakannut'),
    (95, 'Yhteisalueosuuden siirtäminen osakaskiinteistöltä, Lakannut'),
    (96, 'Yhteisalueosuuden tilaksi muodostaminen, Lakannut'),
    (97, 'Kiinteistönmääritys virheen oikaisemiseksi (KML 277.1 §), Lakannut'),
    (98, 'Kiinteistönmääritys osakasluettelon vahvistamiseksi, Lakannut'),
    (99, 'Kiinteistönmääritys, Lakannut'),
    (100, 'Isojako, Lakannut'),
    (105, 'Kuntasiirto, Lakannut'),
    (700, 'Siirtolohkominen, Lakannut'),
    (701, 'Siirtolohkominen koko kiinteistöllä, Lakannut'),
    (702, 'Erillisen vesijätön liittäminen kiinteistöön, Lakannut'),
    (703, 'Selvittämättömän erillisen vesijätön liittäminen kiinteistöön, Lakannut'),
    (704, 'Selvittämättömän erillisen alueen liitäminen kiinteistöön, Lakannut'),
    (705, 'Entisen tiealueen muodostaminen kiinteistöksi, Lakannut'),
    (706, 'Erillisen vesijätön tilaksi muodostaminen, Lakannut'),
    (707, 'Lohkominen, emäkiinteistö jäi kantakiinteistöksi, Lakannut'),
    (708, 'Yleisen alueen lohkominen, Lakannut'),
    (709, 'Yleisen alueen lohkominen, rekisteriyksikkö lakkautettu, Lakannut'),
    (710, 'Tontin lohkominen, Lakannut'),
    (711, 'Tontin lohkominen, rekisteriyksikkö lakkautettu, Lakannut'),
    (712, 'Tontin lohkominen, muodostajakiinteistö jäi kantakiinteistöksi, Lakannut'),
    (713, 'Kiinteistönmääritys, osakasluettelon vahvistaminen, Lakannut'),
    (714, 'Kiinteistönmääritys (KML 101.2 §), Lakannut'),
    (715, 'Yhteisen alueen lunastus, Lakannut'),
    (716, 'Rakennuspaikan osan lunastus, Lakannut'),
    (717, 'Alueen lunastus, Lakannut'),
    (718, 'Alueen lunastus ja liittäminen, Lakannut'),
    (719, 'Ulkopalstan lunastus, Lakannut'),
    (720, 'Yhteismetsän jakaminen, Lakannut'),
    (721, 'Kiinteistön yhdistäminen yhteismetsään, Lakannut'),
    (722, 'Tontinosan lunastus, Lakannut'),
    (723, 'Erityisen oikeuden käyttötarkoituksen muuttaminen, Lakannut'),
    (724, 'Rekisteröity jakosuunnitelman mukaan, Lakannut'),
    (725, 'Maastoliikennelain mukainen reittitoimitus, Lakannut'),
    (726, 'Vesitilusjärjestely, Lakannut'),
    (727, 'Kameraalinen lohkominen, Lakannut'),
    (728, 'Kameraalinen osittaminen, Lakannut'),
    (729, 'Kuntarajan määrääminen Suomen aluevesillä, Lakannut'),
    (730, 'Kameraalinen lohkominen, emäkiinteistö jäi kantakiinteistöksi, Lakannut'),
    (731, 'Rakennusvalvontaviranomaisen päätös (MRL 161-164 §), Lakannut'),
    (732, 'Erillisen alueen liittäminen kiinteistöön, Lakannut'),
    (733, 'Alueellinen yksityistietoimitus koko rekisteriyksiköllä, Lakannut'),
    (734, 'Alueellinen yksityistietoimitus rekisteriyksikön osalla, Lakannut'),
    (735, 'Yhteisen alueen muodostaminen, Lakannut'),
    (736, 'Kiinteistönmääritys, osakasluettelon osittainen vahvistaminen, Lakannut'),
    (737, 'Kiinteistönmääritys, osakasluettelon vahvistaminen, Lakannut'),
    (738, 'Erityistä etuutta koskevan alueen erottaminen yhteiseksi, Lakannut'),
    (739, 'Yleisen tien rajaus tietoimituksessa, Lakannut'),
    (740, 'Yleisen tien rajaus ja liittäminen tietoimituksessa, Lakannut'),
    (741, 'Yhteisalueosuuden lunastus, Lakannut'),
    (742, 'Yhteismetsän muodostaminen, Lakannut'),
    (743, 'Alueen liittäminen yhteismetsään, Lakannut'),
    (744, 'Yleisen vesialueen laajentaminen, Lakannut'),
    (745, 'Kameraalisen jaotuksen muutos, Lakannut'),
    (746, 'Kuntajaon muutos, Lakannut'),
    (747, 'Toimituksen tai päätöksen poistaminen (OK 31 luku), Lakannut'),
    (748, 'Toimituksen tai päätöksen purkaminen (KML 278.2 §), Lakannut'),
    (749, 'Kiinteistön laadun muuttaminen, Lakannut'),
    (750, 'Tontin muodostaminen tunnusmuutoksella, Lakannut'),
    (1004, 'Käyttöoikeuden säilyttäminen, Lakannut'),
    (1009, 'Maankäyttörajoituksen lisääminen, Lakannut'),
    (1010, 'Maankäyttörajoituksen kohdistaminen, Lakannut'),
    (1012, 'Käyttöoikeuden poisto päätöksellä, Lakannut'),
    (1014, 'Kaavamerkinnän poisto, Lakannut'),
    (1015, 'Maankäyttörajoituksen poisto, Lakannut'),
    (1021, 'Puuttuvan oikeuden lisääminen, Lakannut'),
    (1022, 'Puuttuvan merkinnän lisääminen, Lakannut'),
    (1052, 'Merkinnän osan muutos käyttöoikeusyksiköksi, Lakannut'),
    (1085, 'Tonttijaon poisto, Lakannut'),
    (1102, 'Lohkominen koko rekisteriyksiköllä, Lakannut'),
    (1110, 'Lohkominen, Lakannut'),
    (1111, 'Lohkominen luovuttajan tunnusta muuttamatta, Lakannut'),
    (1120, 'Lohkominen määräalaa siirtämällä, Lakannut'),
    (1130, 'Lohkominen koko kiinteistöllä, Lakannut'),
    (1140, 'Lohkominen määräalaa siirtämällä koko kiinteistöllä, Lakannut'),
    (1150, 'Lohkominen kumotun asemakaavan alueella, Lakannut'),
    (1160, 'Lohkominen rekisteriyksikköön liittämällä, Lakannut'),
    (1161, 'Lohkominen liittäen koko kiinteistö rekisteriyksikköön, Lakannut'),
    (1162, 'Lohkominen liittäen luovuttajan tunnusta muuttamatta, Lakannut'),
    (1250, 'Jakosuunnitelma, Lakannut'),
    (1410, 'Erillisen vesijätön tilaksi muodostaminen, Lakannut'),
    (1413, 'Erillisen vesijätön kiinteistöön liittäminen, Lakannut'),
    (1414, 'Erillisen vesijätön tilaksi muodostaminen, Lakannut'),
    (1420, 'Erillisen vesijätön kiinteistöön liittäminen, Lakannut'),
    (1452, 'Yleiseen tarpeeseen erotetun alueen muodostaminen rekisteriyksiköksi, Lakannut'),
    (1453, 'Yleiseen tarpeeseen erotetun alueen liittäminen tilaan, Lakannut'),
    (1460, 'Lisäalueen liittäminen yleiseen alueeseen, Lakannut'),
    (1500, 'Yleisen vesialueen laajentaminen, Lakannut'),
    (1600, 'Yhteisalueosuuden selvittäminen, Lakannut'),
    (1606, 'Yhteisen alueen jako kokonaan, Lakannut'),
    (1609, 'Yhteisen alueen jako ja kiinteistöön liittäminen kokonaan, Lakannut'),
    (1638, 'Osakasluettelon osittainen vahvistaminen, Lakannut'),
    (1655, 'Erityisen etuuden siirto, Lakannut'),
    (1660, 'Erityisen etuuden lakkauttaminen, Lakannut'),
    (1722, 'Yhteisen alueen lunastus koko rekisteriyksiköllä, Lakannut'),
    (1732, 'Rakennuspaikan osan lunastus koko rekisteriyksiköllä, Lakannut'),
    (1742, 'Alueen lunastus koko rekisteriyksiköllä, Lakannut'),
    (1743, 'Alueen lunastus ja liittäminen koko rekisteriyksiköllä, Lakannut'),
    (1746, 'Yleisen tien lunastus ja liittäminen koko rekisteriyksiköllä, Lakannut'),
    (1747, 'Yleisen tien lunastus koko rekisteriyksiköllä, Lakannut'),
    (1753, 'Entisen tiealueen liittäminen rekisteriyksikköön, Lakannut'),
    (1756, 'Entisen tiealueen liittäminen rekisteriyksikköön, Lakannut'),
    (1758, 'Entisen tiealueen muodostaminen kiinteistöksi, Lakannut'),
    (1762, 'Ulkopalstan lunastaminen koko rekisteriyksiköllä, Lakannut'),
    (1765, 'Vähäisen alueen lunastaminen koko rekisteriyksiköllä (KML 79§), Lakannut'),
    (1801, 'Tontinmittaus, Lakannut'),
    (1802, 'Tontinmittaus koko rekisteriyksiköllä, Lakannut'),
    (1851, 'Yleisen alueen mittaus, Lakannut'),
    (1852, 'Yleisen alueen mittaus koko rekisteriyksiköllä, Lakannut'),
    (1890, 'Merkitseminen ilman mittausta, Lakannut'),
    (1902, 'Tilusjärjestely koko rekisteriyksiköllä, Lakannut'),
    (1917, 'Rakennusmaan järjestely koko rekisteriyksiköllä, Lakannut'),
    (1919, 'Rakennusmaan järjestely koko rekisteriyksiköllä, muodostaen, Lakannut'),
    (2120, 'Rajamerkkien siirto, Lakannut'),
    (2320, 'Rasitteen selvittäminen, Lakannut'),
    (2330, 'Erityisen etuuden selvittäminen, Lakannut'),
    (2410, 'Osakasselvittely, Lakannut'),
    (2510, 'Toimitusasiakirjojen selvittäminen, Lakannut'),
    (2530, 'Alueen omistajan selvittäminen, Lakannut'),
    (3020, 'Päätöksen muuttaminen (KML 278.1 §), Lakannut'),
    (3030, 'Toimituksen purkaminen (KML 278.2 §), Lakannut'),
    (3036, 'Muodostumisen purkaminen (KML 278.2 §), Lakannut'),
    (3038, 'Muodostumisen purkaminen peruttu, Lakannut'),
    (3040, 'Päätöksen purkaminen (KML 278.2 §), Lakannut'),
    (3200, 'Kiinteistörekisteristä poistaminen, Lakannut'),
    (3700, 'Rekisterimerkintä peruttu, Lakannut'),
    (3808, 'Lakkautus peruttu toimituksen purkamisessa, Lakannut'),
    (3910, 'Puutteellisen merkinnän lisäys tai täydentäminen, Lakannut'),
    (4100, 'Rekisteriyksiköiden yhdistäminen, Lakannut'),
    (4200, 'Kuntajaon muutos, Lakannut'),
    (4210, 'Kameraalisen jaotuksen muutos, Lakannut'),
    (4220, 'Kameraalinen lohkominen, Lakannut'),
    (4235, 'Kameraalinen osittaminen koko rekisteriyksiköllä, Lakannut'),
    (4237, 'Kameraalinen osittaminen ja liittäminen koko rekisteriyksiköllä, Lakannut'),
    (4500, 'Yksikön rasitteet ja käyttöoikeudet selvitetty, Lakannut'),
    (4600, 'Yksikön yhteisalueosuudet selvitetty, Lakannut'),
    (4690, 'Jako päättynyt, Lakannut'),
    (4701, 'Tontinmittauksen/lohkomisen rekisteröinti kesken, Lakannut'),
    (4702, 'Yleisen alueen mittauksen/lohkomisen rekisteröinti kesken, Lakannut'),
    (4710, 'Kiinteistön laadun muuttaminen kesken, Lakannut'),
    (4810, 'Tontinosan lunastaminen, Lakannut'),
    (4812, 'Koskiensuojelulain mukainen korvauksen määrääminen, Lakannut'),
    (4850, 'Päätös rekisterinpitäjästä, Lakannut'),
    (4851, 'Rekisterinpitäjätiedon korjaaminen, Lakannut'),
    (6000, 'Kaivospiiritoimitus, Lakannut'),
    (6071, 'Pinta-ala muuttunut muodostamishetken jälkeen, Lakannut');
